[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
linker = "flip-link"
rustflags = ["-C", "link-arg=-Tlink.x"]
runner = "probe-rs run --chip STM32F407VGTx"

[env]
DEFMT_LOG = "info"
